/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnswersRouteImport } from './routes/answers'
import { Route as DevRouteImport } from './routes/dev'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as PlayRouteImport } from './routes/play'
import { Route as StatsRouteImport } from './routes/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersRoute = AnswersRouteImport.update({
  id: '/answers',
  path: '/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answers': typeof AnswersRoute
  '/dev': typeof DevRoute
  '/how-to-play': typeof HowToPlayRoute
  '/play': typeof PlayRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answers': typeof AnswersRoute
  '/dev': typeof DevRoute
  '/how-to-play': typeof HowToPlayRoute
  '/play': typeof PlayRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answers': typeof AnswersRoute
  '/dev': typeof DevRoute
  '/how-to-play': typeof HowToPlayRoute
  '/play': typeof PlayRoute
  '/stats': typeof StatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/answers' | '/dev' | '/how-to-play' | '/play' | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/answers' | '/dev' | '/how-to-play' | '/play' | '/stats'
  id:
    '__root__' | '/' | '/answers' | '/dev' | '/how-to-play' | '/play' | '/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswersRoute: typeof AnswersRoute
  DevRoute: typeof DevRoute
  HowToPlayRoute: typeof HowToPlayRoute
  PlayRoute: typeof PlayRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers': {
      id: '/answers'
      path: '/answers'
      fullPath: '/answers'
      preLoaderRoute: typeof AnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswersRoute: AnswersRoute,
  DevRoute: DevRoute,
  HowToPlayRoute: HowToPlayRoute,
  PlayRoute: PlayRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
